name: Tests

on: [push, pull_request]

jobs:
  test:

    name: Test on Python ${{ matrix.py_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: [2.7, 3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.py_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install mock for Python 2.7
      run: pip install mock
    - name: Run tests
      run: python setup.py test
